### ISSUE TITLE
TypeError: unsupported format string passed to list.__format__

### ISSUE THREAD

**Issue by nuomizai** [bradyz/2020_CARLA_challenge#10]
I met this error when I ran the run_agent.sh

Traceback (most recent call last):
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 380, in main
    leaderboard_evaluator.run(arguments)
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 333, in run
    StatisticsManager.save_global_record(global_stats_record, self.sensors, args.checkpoint)
  File "/home/quan/2020_CARLA_challenge/leaderboard/leaderboard/utils/statistics_manager.py", line 257, in save_global_record
    '{:.3f}'.format(stats_dict['infractions']['collisions_layout']),
TypeError: unsupported format string passed to list.__format__

and I printed stats_dict['infractions']['collisions_layout'] by adding the code

`print('infraction:', stats_dict['infractions']['collisions_layout'], stats_dict['infractions']['collisions_pedestrian'])
`
the result was:

infraction: [] []

It seemed that the list object cannot  using '{:.3f}'.format. I wanted to figure out what was the contend should be in the infraction list, the pedestrains' id or the total infraction numbers? And how can I fix this misformat properly? Thank you.

**Comment by bradyz** [comment]
I usually see this error when there is some sort of runtime error during the route
were there any other errors before what you pasted?

**Comment by nuomizai** [comment]
It seemed that this problem was related to the issue in #11 . After I fixed the problem in #11 , this misformat problem has gone. Thank you, @bradyz .
