### ISSUE TITLE
Error when running run_evaluation.sh

### ISSUE THREAD

**Issue by abdallahaymaan** [bradyz/2020_CARLA_challenge#13]
Traceback (most recent call last):
  File "/home/abdallahaymaan/2020_CARLA_challenge/leaderboard/leaderboard/leaderboard_evaluator.py", line 26, in <module>
    import carla
ModuleNotFoundError: No module named 'carla'

although the stated exports were done including the CARLA_ROOT

has anyone encountered such issue?
any help will be appreciated!

**Comment by bradyz** [comment]
can you paste the full command you ran?

**Comment by abdallahaymaan** [comment]
export PORT=2000
export DEBUG_CHALLENGE=0
export REPETITIONS=1
export ROUTES=/home/abdallahaymaan/2020_CARLA_challenge/leaderboard/data/routes_devtest.xml
export CHECKPOINT_ENDPOINT=tmp.txt
export SCENARIOS=/home/abdallahaymaan/2020_CARLA_challenge/leaderboard/data/all_towns_traffic_scenarios_public.json
export CARLA_ROOT=/home/abdallahaymaan/CARLA_0.9.9
conda activate carla.9
then inside the 2020_CARLA_challenge dir
./leaderboard/scripts/run_evaluation.sh

Also i edited the second line in run_evaluation.sh
**from**
python ${LEADERBOARD_ROOT}/leaderboard/leaderboard_evaluator.py \
**to** 
python /home/abdallahaymaan/2020_CARLA_challenge/leaderboard/leaderboard/leaderboard_evaluator.py \

OUTPUT:

Traceback (most recent call last):
  File "/home/abdallahaymaan/2020_CARLA_challenge/leaderboard/leaderboard/leaderboard_evaluator.py", line 26, in <module>
    import carla
ModuleNotFoundError: No module named 'carla'

**Comment by abdallahaymaan** [comment]
what I want to do is to visualize the results of the pretrained model (epoch=24.ckpt) through tables.
a route_19.txt was created containing data regarding the results of the run,  is visualizing it possible?

**Comment by abdallahaymaan** [comment]
Also running the dataset.py file didnot work it returns an error saying

> ImportError: attempted relative import with no known parent package

although the imports has nothing wrong, is running it directly to fix the topview issue the right thing to do?

**Comment by bradyz** [comment]
sure thing, the route_19.txt should be in json

I recommend you run exactly the command in the README, not the run_evaluation.sh script directly.
