### ISSUE TITLE
Not the exact same implementation as the original LBC code ?

### ISSUE THREAD

**Issue by jrabary** [bradyz/2020_CARLA_challenge#15]
Hi,

I wondering whether  this base code implements exactly the original LBC algorithm. When I look at it closely
it seems that it doesn't use the branch selection based on command (follow lane, turn left, ...)
Instead it seems to use the target points coordinates.
Am I correct ?

**Comment by bradyz** [comment]
Correct! The conditional command here is a "target heatmap", which is the target point projected into the camera view. I found this to work a little better, but have yet to evaluate this quantitatively

**Comment by jrabary** [comment]
Thanks. Interesting result. I think there is less ambiguity when one use the target heatmap instead of the high level command. That may explain the performance gain if validated.

**Comment by AIasd** [comment]
Hi @bradyz  can you explain a bit more about this target heatmap? I am really interested in knowing a bit more about it.

**Comment by bradyz** [comment]
So instead of using discrete commands, we render the project the future waypoint (this is typically pretty far, maybe 50 meters or so) into the first person view as a heatmap, then concatenate this to the RGB image.

**Comment by AIasd** [comment]
I see. This makes sense. Thank you for the quick response!
