### ISSUE TITLE
Why the GPS position is normalised with mean and scale ?

### ISSUE THREAD

**Issue by jrabary** [bradyz/2020_CARLA_challenge#2]
Hi,
Thanks for sharing this implementation. It really helps to understand how the new Carla challenge works. 

I'm wondering why are you normalising the GPS position in your planner as defined in this function 

https://github.com/bradyz/leaderboard/blob/115cd61bd57a29ea590ed9411db2d2753ed1cd4f/team_code/planner.py#L50

And where are those normalisation values come from ?

**Comment by bradyz** [comment]
This is a hack to get the GPS coordinates into "world coordinates", as in the coordinates you would get if you did vehicle.get_location()

I found these values by fitting a mapping to these off towns 1 and 2

EDIT: a little more reasoning why we do this - world coordinates is a lot easier to reason about than GPS coordinates (gps coordinates are extremely large in scale (1 unit =  multiple km), after we normalize, 1 unit is about 1 meter).
