### ISSUE TITLE
TrafficManager issue when running parallel instances

### ISSUE THREAD

**Issue by aleallievi** [bradyz/2020_CARLA_challenge#20]
Hi @bradyz 
I am trying to run multiple parallel instances of the _leaderboard_evaluator.py__ with your agent. However I am getting the following error:
```
"The scenario cannot be loaded
trying to create rpc server for traffic manager; but the system failed to create because of bind error."
```
It seems to be an issue with setting different tm-port arguments for each client; all clients currently seem to be trying to attach to the original traffic manager server and fail. However I don't see where this can be done in the current code base.
Any idea on how to get around this?
Many thanks in advance

**Comment by bradyz** [comment]
i believe in the newer version of the leaderboard the traffic manager port is able to be changed,
however i have not gotten around to updating to the most recent versions :(

i'll work on updating the leaderboard and scenario_runner dependencies to their latest versions, but this won't happen until later this month

**Comment by aleallievi** [comment]
Ok great - Thanks for the quick reply, and good luck with everything. Many greetings to Philipp, and hope to see you soon around UT 👍 .
