### ISSUE TITLE
model does not pass tests on 0.9.10

### ISSUE THREAD

**Issue by saurabhjha1** [bradyz/2020_CARLA_challenge#23]
Hi, 

I am trying to run the model (epoch=24.chkpt) mentioned on the readme doc. However, I see that the tests are failing especially with respect to steering. 

Any pointers as to what may be going wrong. I am guessing it is the updated carla version that is not compatible with the trained model. .

Saurabh

**Comment by bradyz** [comment]
the model is not so good at Town01 and Town02 due to the relatively hard turns,
probably due to the low level controller (PID)

you can try playing around with the PID values,
but the behavior you're seeing is expected, and a failure mode of our approach!

**Comment by saurabhjha1** [comment]
Thanks for your quick response!

Are there test cases that the model will pass at the moment ?

**Comment by bradyz** [comment]
I can't remember off the top of my head
try some of the later routes - maybe routes 20+ will do better

**Comment by saurabhjha1** [comment]
Got it! Seems like it works okay on route 24!
