### ISSUE TITLE
Some issue in Data collection for Carla 0.9.10

### ISSUE THREAD

**Issue by t27** [bradyz/2020_CARLA_challenge#24]
While running the data collection code on 0.9.10 we found some issues that mostly seem like they were caused due to some breaking changes in Carla 0.9.9 -> 0.9.10  

This one seems like an issue in the scenario runner import where the name of the AgentPool was changed to DataProvider, 
https://github.com/bradyz/leaderboard/blob/35fb5f2d1e7d8884d20d92e492f5d49ecbae2b65/team_code/map_agent.py#L1

Over here the semantic segmentation remapping is not compatible with the larger semantic segmentation outputs in carla 0.9.10 ([Old](https://carla.readthedocs.io/en/0.9.9/ref_sensors/#semantic-segmentation-camera) vs [New](https://carla.readthedocs.io/en/0.9.10/ref_sensors/#semantic-segmentation-camera))
https://github.com/bradyz/carla_project/blob/2f0c166167a8d44b8b720cdbcd5d56983fa71602/src/common.py#L4

I can submit a PR for the above changes if needed as well, I would just need some help with the new segmentation class mappings, do let me know if I can help,

Thanks!

**Comment by bradyz** [comment]
thanks for the detailed issue!

I've fixed these in the newest commit a05ab7b and the data collection should work in 0.9.10.1 now

**Comment by omerXfaruq** [comment]
Hello @t27 can you currently collect data, I have problems in data_collection here: https://github.com/bradyz/2020_CARLA_challenge/issues/31
Is your problem solved, how do you currently collect data, I want to collect segmentation_data.
Thank you very much!

**Comment by t27** [comment]
Yeah, I was able to collect data. Although at the time i posted the issue, we chose to collect data from Carla 0.9.9 instead of 0.9.10 as we were short of time and using 0.9.9 in that version of the repository was the fastest way. Although the code is updated now and it should be working with 0.9.10 now.

I faced a similar issue as #31, I've commented there with what worked for me
