### ISSUE TITLE
RawController And PidController

### ISSUE THREAD

**Issue by omerXfaruq** [bradyz/2020_CARLA_challenge#25]
Hello there;

As far as I can see training in carla_project/src/image_model and carla_project/src/map_model is done with RawController which is a small network. However benchmark in leaderboard/team_code/image_agent uses PIDController. What is the reason for difference between training controller and benchmark controller?

Thank you for your attention;

**Comment by bradyz** [comment]
ah those were some old experiments to see which output would be better - low level actions or mid level waypoints

our submission uses the waypoints, so you can simply ignore the rawcontroller

**Comment by omerXfaruq** [comment]
Ok, thanks!

**Comment by omerXfaruq** [comment]
@bradyz a question still lingers in my mind, as far as I can see rawController is used in image_model.py while training, and it also affects the loss. So is training done with a different controller, and benchmark is using pid controller? Is the current state of the training part is correct?

**Comment by bradyz** [comment]
No problem, for training, just set `command_coefficient = 0`
