### ISSUE TITLE
./run_agent.sh core dump on carla0.9.10.1

### ISSUE THREAD

**Issue by dearxieyali** [bradyz/2020_CARLA_challenge#26]
(env) dcv-user@ip-172-31-0-220:~/2020_CARLA_challenge$ ./run_agent.sh
route_00_10_27_12_34_39
Preparing scenario: RouteScenario_0
ScenarioManager: Running scenario RouteScenario_0
index 21 is out of bounds for axis 0 with size 16
Traceback (most recent call last):
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 379, in main
    leaderboard_evaluator.run(arguments)
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 331, in run
    global_stats_record = self.statistics_manager.compute_global_statistics(route_indexer.total)
  File "/home/dcv-user/2020_CARLA_challenge/leaderboard/leaderboard/utils/statistics_manager.py", line 206, in compute_global_statistics
    route_length_kms = route_record.scores['score_route'] * route_record.meta['route_length'] / 1000.0
KeyError: 'route_length'
./run_agent.sh: line 23:  7717 Segmentation fault      (core dumped) python leaderboard/leaderboard/leaderboard_evaluator.py --challenge-mode --track=dev_track_3 --scenarios=leaderboard/data/all_towns_traffic_scenarios_public.json --agent=${TEAM_AGENT} --agent-config=${TEAM_CONFIG} --routes=${ROUTES} --checkpoint=${CHECKPOINT_ENDPOINT} --port=${PORT}
Done. See sample_data1/route_00.txt for detailed results.

**Comment by bradyz** [comment]
make sure to update the leaderboard submodule
