### ISSUE TITLE
Trying  To Record With run_agent.sh

### ISSUE THREAD

**Issue by omerXfaruq** [bradyz/2020_CARLA_challenge#28]
Hello There;

I am trying to record with 
"--record=/home/ubuntu/learning-by-cheating/recordings/" 

-However it has some error. It says no such file or directory. Shall I give file path or directory path to the  --record variable? I checked the "/home/ubuntu/learning-by-cheating/recordings/" directory, it is available.

https://files.slack.com/files-pri/TMMCBKX2N-F01DP9BQMC2/image.png

-Another error is failed to destroy actor xxx. Is it a common error?

Also a ss from detailed results:
https://files.slack.com/files-pri/TMMCBKX2N-F01D8JJE27R/image.png

Thanks a lot;

**Comment by Hither1** [comment]
does manually creating the directory help?

**Comment by omerXfaruq** [comment]
haha, it has been quite a while since I created this issue, I don't know :D
