### ISSUE TITLE
Velocity, Target As Input

### ISSUE THREAD

**Issue by omerXfaruq** [bradyz/2020_CARLA_challenge#29]
Hello;

I am confused about target entering to neural net as input. At first I thought it as velocity however after searching the issues I found that it is a 50 meter away future target.

-Don't you use velocity as input like in LBC original repo?
-How do you calculate position of the target? And what are the modifications happening to target, do you project the target position onto the camera and heatmap?

**Comment by bradyz** [comment]
here we don't use velocity as input

the position of the far away target is given during test time - this is essentially the route the ego vehicle is supposed to go,
but there's lots of noise in this due to GPS, and it is heavily downsampled (only given every 50m or so)
