### ISSUE TITLE
How to collect the data with extra pedestrians in the background?

### ISSUE THREAD

**Issue by Jimuyangz** [bradyz/2020_CARLA_challenge#3]
Hi,
I am trying to collect my own data using the documented way. However, it seems I could only control the number of vehicles in the background and I could not add pedestrians. I wonder if there is any way to add pedestrians to the scenario in your code?

And I also saw another data collection script https://github.com/bradyz/carla_project/blob/2f0c166167a8d44b8b720cdbcd5d56983fa71602/src/collect_data.py
I wonder what this one is used for? Thanks!

**Comment by bradyz** [comment]
Currently, I don't believe pedestrians are in the CARLA challenge (besides the emergency stop scenario, where the pedestrian runs out in the middle of the street).

So this is currently not supported.
