### ISSUE TITLE
HAS_DISPLAY and DEBUG_CHALLENGE's effects

### ISSUE THREAD

**Issue by omerXfaruq** [bradyz/2020_CARLA_challenge#32]
Hello There;

```
export DEBUG_CHALLENGE=1
export HAS_DISPLAY=1

```
I put these lines into run_agent.sh but nothing happens? I expected them to generate a window like this:
https://github.com/bradyz/2020_CARLA_challenge/blob/master/assets/sample_route.gif

What are their efffect?

**Comment by bradyz** [comment]
you should see a window like that pop up - make sure your DISPLAY environmental variable is set up correctly

additionally you can just check to see if any `cv.imshow` works on your machine

**Comment by omerXfaruq** [comment]
Oh what an old issue :)

How are you doing @bradyz? Are you still working on e2e autonomous driving and Carla?

**Comment by bradyz** [comment]
lol nice to hear from you :) - doing a bit more vision recently but still keeping up with planning / e2e!
not much CARLA stuff lately though :(

**Comment by omerXfaruq** [comment]
Good work :)
