### ISSUE TITLE
Segmentation model weights?

### ISSUE THREAD

**Issue by aaronh65** [bradyz/2020_CARLA_challenge#38]
Hey Brady,

I'm interested in deploying an agent using the Segmentation model (I guess this would be the privileged agent referred to in the LBC writeup) on the Leaderboard routes. I tried looking for model weights on Weights and Biases, but I think the only ones available there are the sensorimotor (image model) weights. Are there any Seg model weights on WandB? If not, would you consider making them available?

**Comment by bradyz** [comment]
They're up there as well - i've updated the tags now to tell if they're privileged or sensorimotor

![image](https://user-images.githubusercontent.com/7716849/102723662-0c7b4200-42cf-11eb-9e8b-ee27c54018c9.png)

**Comment by aaronh65** [comment]
Thanks! Appreciate the help.
