### ISSUE TITLE
route_19.xml, route_15, route_10 does not work

### ISSUE THREAD

**Issue by FitashUlHaq** [bradyz/2020_CARLA_challenge#39]
Hi, 

I am trying to run the pre-trained model and it is failing on almost every route. I have tried route 10, 15, 19, can it be the configuration error or DNN accuracy problem?

**Comment by bradyz** [comment]
it could be an issue with carla versions - i haven't tested this on the more recent versions
what version are you using?

**Comment by FitashUlHaq** [comment]
0.9.10.1

**Comment by raozhongyu** [comment]
I meet this same question, Have you solved it or tried this work with different version

**Comment by FitashUlHaq** [comment]
> I meet this same question, Have you solved it or tried this work with different version

Unfortunately no, it didn't work for me

**Comment by raozhongyu** [comment]
Thanks for your reply

**Comment by FitashUlHaq** [comment]
any update regarding this?

**Comment by bradyz** [comment]
if you could attach some sample video of a run or two it would help tell where the issue is!
