### ISSUE TITLE
team_code/image_agent.py not found

### ISSUE THREAD

**Issue by FitashUlHaq** [bradyz/2020_CARLA_challenge#4]
Hi, 

I am unable to find this file and the last commit shows this is removed, is it possible to run it without this file?

**Comment by bradyz** [comment]
this is now located in the leaderboard code, let me make sure everything is running smoothly and update the readme!

**Comment by FitashUlHaq** [comment]
thank you, much appreciated

**Comment by bradyz** [comment]
can i ask what is the command you're running?

**Comment by FitashUlHaq** [comment]
I was trying to run the pretrained model where the command is
export TEAM_AGENT=scenario_runner/team_code/image_agent.py  # no need to change
I tried to see the image_agent in team_code in scenario_runner but couldnt find it

**Comment by bradyz** [comment]
if you do
export TEAM_AGENT=image_agent.py

does it work?

i'd also recommend updating all the submodules, specifically the leaderboard submodule

**Comment by FitashUlHaq** [comment]
with this
 export TEAM_AGENT=image_agent.py
it works.

Thank you!
