### ISSUE TITLE
CoordConverter

### ISSUE THREAD

**Issue by raozhongyu** [bradyz/2020_CARLA_challenge#43]
Thanks for your great work, I have some questions about the CoordConverter in train_image1. I'd like to konw that if i change the image size to (192,192), shall I change the  world_y and fixed_offset

**Comment by bradyz** [comment]
modify the intrinsics in `converter.py`
try to visualize the data using the script provided in the README to see if it looks reasonable and you can update here if there's anything odd

**Comment by raozhongyu** [comment]
Thanks for your reply
