### ISSUE TITLE
Where can I download the teacher model

### ISSUE THREAD

**Issue by AviP1234** [bradyz/2020_CARLA_challenge#45]
Hi,
Thanks, both for the innovative research and for sharing the code with the community.
I didn't understand how to download the teacher model, in order to use the image_model.py to train the non-privilege agent.
Can you add a link for the model?
Thanks

**Comment by bradyz** [comment]
The model weights can be downloaded from the [wandb project](https://wandb.ai/bradyz/2020_carla_challenge_lbc?workspace=user-bradyz)

Click on any run, navigate to the "files" tab on the left panel,
then you should be able to download a teacher - [here's an example](https://wandb.ai/bradyz/2020_carla_challenge_lbc/runs/command_coefficient=0.01_sample_by=even/files?workspace=user-bradyz)

![image](https://user-images.githubusercontent.com/7716849/144285684-88854df2-dedd-4024-aa38-f893182f7d5a.png)
