### ISSUE TITLE
Trying to update to work with CARLA 0.9.13

### ISSUE THREAD

**Issue by ajdroid** [bradyz/2020_CARLA_challenge#49]
I see that the scenario runner and leaderboard submodules in your repo are forks of the carla ones and seem to have been updated to 0.9.10 (from 0.9.7, it looks like using one large merge commit). Do you have any custom changes in here, or are they just the 0.9.10 compatible versions of those 2 repositories?

I ask because I'm trying to update this code to work with the latest Carla. However, the PythonAPI has several changes which will necessitate updates to these submodules and I don't want to miss any custom changes you may have had during that update if I update from the vanilla Carla versions

**Comment by bradyz** [comment]
Hello! Thanks for the interest - I don't think there's any edits from our side that are version specific.
There have been a lot of changes with the latest CARLA though so it might get be a little bit of work.

I won't update this repo since I am lazy :(, but if you have specific errors you run into you can post them here and I'd be happy to try and help!

**Comment by ajdroid** [comment]
Thanks for your response! 
I wanted to clarify that the 2 submodules which come from carla (`scenario_runner` and `leaderboard`) are unmodified by you (except for the `team_code` folder within `leaderboard`)? Or are you saying that you have edits but they should translate across carla versions? My plan is to just get the 0.9.13 compatible versions of those 2 from the carla-simulator github org. Then, the only code I would need to update is only the code in the [carla_project](https://github.com/bradyz/carla_project/) and the `team_code` folder. Am I understanding correctly?

**Comment by ajdroid** [comment]
Hi Brady, one other question -- what does the mean and scale correspond to here?
https://github.com/bradyz/leaderboard/blob/7104247204e0e591d43640d2c98490533bc5bbb8/team_code/planner.py#L45
```python
class RoutePlanner(object):
    def __init__(self, min_distance, max_distance, debug_size=256):
        self.route = deque()
        self.min_distance = min_distance
        self.max_distance = max_distance

        self.mean = np.array([49.0, 8.0])
        self.scale = np.array([111324.60662786, 73032.1570362])
```

EDIT: For posterity, the answer can be found here: https://github.com/autonomousvision/transfuser/issues/48#issuecomment-1054376659
