### ISSUE TITLE
Train-val-test split of dataset in the pre-trained model

### ISSUE THREAD

**Issue by saashanair** [bradyz/2020_CARLA_challenge#5]
Hi, first of all thanks for this repo. 
I was wondering, for the pre-trained model provided by you, how did you split the dataset? Did you train the model on all 76 routes, if not, could you let me know which routes you used for training? Also, if I understand correctly, the 76 routes in the leaderboard/data/routes folder are extracted from the routes_training, routes_debug and routes_devtest files provided in the CARLA Challenge, right?

Thanks in advance. 😄

**Comment by bradyz** [comment]
The routes are extracted from those routes_training.xml and routes_devtest.xml

as for the data provided, i'm not actually sure which correspond to each route since the naming convention is just the timestamp

For another submission this year, i'll make sure the naming is more principled :)

**Comment by saashanair** [comment]
Thanks for the prompt response. :)
Sorry, I didn't catch the answer to this, so does that mean the pre-trained model available for download on WandB was trained on all 76 routes? Or just the routes provided in the routes_training.xml?

**Comment by bradyz** [comment]
the pre-trained model uses the 76 routes for train/val,
but i'm not sure which routes are used for val since each episode only contains timestamp information

**Comment by saashanair** [comment]
Understood. Thanks a ton for the response! :)
