### ISSUE TITLE
cannot find image_agent.py

### ISSUE THREAD

**Issue by Hither1** [bradyz/2020_CARLA_challenge#50]
Dear authors,

May I ask where is the image_agent.py file?

**Comment by ajdroid** [comment]
It's here: https://github.com/bradyz/carla_project/tree/ac791fcf7e59ad80b6908dadc00eb4f26147c065/src
Did you clone all the submodules as instructed in the readme?

**Comment by Hither1** [comment]
Found it now. Thanks
