### ISSUE TITLE
topdown segmentation images were all black

### ISSUE THREAD

**Issue by nuomizai** [bradyz/2020_CARLA_challenge#6]
After I downloaded the full dataset provided in this project, I found that the topdown png picitures were all black. And I opened several route folders, but the segmentation images were the same (all black). Why this happened? Did that mean that I can not use the topdown segmentation images for training?

**Comment by bradyz** [comment]
The top down segmentation is encoded as class IDs (0 through number of classes)
This is why it looks black
Run the dataset.py script to see it colorized

**Comment by nuomizai** [comment]
> The top down segmentation is encoded as class IDs (0 through number of classes)
> This is why it looks black
> Run the dataset.py script to see it colorized

Thank you, @bradyz . I have run the dataset.py and seen the topdown segmentation results successfully. By the way, in your paper, you mentioned that your model was also tested under NoCrash Benchmark. So, how can I test the agent in this project under that benchmark? Do you have any code demenstration? Thank you for your help :)

**Comment by bradyz** [comment]
The benchmark for that is a little different, check out the original repo https://github.com/dianchen96/LearningByCheating for information on how to run the NoCrash benchmark

**Comment by nuomizai** [comment]
All right. Thank you! @bradyz
