### ISSUE TITLE
Dataset generation script

### ISSUE THREAD

**Issue by shiba24** [bradyz/2020_CARLA_challenge#7]
Hi, thank you for your detailed explanation!

I have a question - in README, you are mentioning `scenario_runner/team_code/autopilot.py`.
But there is no autopilot.py or team_code directory at the repository https://github.com/bradyz/scenario_runner/tree/8752705cbbcb6e34a1a09437fc58e727d59d0f06

If I want to reuse your dataset generation script, what should I use?

Thank you!

**Comment by bradyz** [comment]
The autopilot is now located in  `leaderboard/team_code/autopilot.py`,
i'll update the README asap, thanks for bringing this up

**Comment by shiba24** [comment]
gocha, thanks for the quick response
