### ISSUE TITLE
DNN not working properly

### ISSUE THREAD

**Issue by FitashUlHaq** [bradyz/2020_CARLA_challenge#8]
Hi, 

I am executing the steps mentioned in the docs but DNN seemed to be working incorrectly I have tried it for route 00 and route 19, and for both it goes out of lane (picture of route 00 attached).

Is it supposed to happen this way or am i doing something incorrect?
![Screenshot from 2020-06-29 10-07-03](https://user-images.githubusercontent.com/15017524/85989216-81408400-b9f0-11ea-80e2-d7bed509ede1.png)

**Comment by bradyz** [comment]
Try a different route, maybe one of the later ones like 40

the released model struggles on towns 01 and 02 due to these tight turns due to the PID controller and the data distribution (towns 01 and 02 have shorter routes compared to the later towns)

our submission this year will try to address these issues :)

**Comment by FitashUlHaq** [comment]
Hii, any update on the newer model ? :)

**Comment by bradyz** [comment]
slow and steady progress - currently working on making the autopilot better maybe 2 weeks ETA

**Comment by FitashUlHaq** [comment]
Hii, any update on the newer model? I am unable to access the [link](https://app.wandb.ai/bradyz/2020_carla_challenge_lbc/runs/command_coefficient=0.01_sample_by=even_stage2/files). it says "This site can’t be reached"

**Comment by bradyz** [comment]
try the latest commit - also try the link again

**Comment by FitashUlHaq** [comment]
can you please give me the link? [this](https://wandb.ai/bradyz/2020_carla_challenge_lbc?workspace=user-) project shows the latest commit to be 6 months old. 

Many thanks in advance

**Comment by bradyz** [comment]
those checkpoints still work - the code updates for the latest CARLA version 0.9.10.1 are located in this repo https://github.com/bradyz/2020_CARLA_challenge
